---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:5.0.3-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"

  leia:
    build: .
    depends_on:
      - kafka
      - redis
    volumes:
      - ./example-config:/etc/config/
    ports:
      - 80:80

