createIngress: true
replicaCount: 2
image:
  repository: zensum/leia
  tag: latest
  pullPolicy: IfNotPresent
env: {}
resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
serviceType: NodePort
ingressClass: gce